Expose sign and verify methods
gr2m/octokit-webhooks.js-legacy pull request #2
Opened 2017-10-30 02:09 UTC by bkeepers

I needed a way to easily generate/verify the webhook signature for some proper integration tests in @probot. This exposes a `sign` and `verify` method on the webhook handler that can be used to generate and verify the signatures for the given webhook secret.

Usage:

```js
const createHandler = require('github-webhook-handler')
const handler = createHandler({ path: '/webhook', secret: 'myhashsecret' })

const sig = handler.sign({foo: 'bar'})
handler.verify(sign, {foo: 'bar'})
```

2017-10-30 21:23 UTC, gr2m requested changes
needs tests for the new public APIs. Let me know if you want me to look into it :)

2017-10-31 01:42 UTC, bkeepers commented
Updated tests to use `.sign`, and added tests for `sign`+`verify`.

2017-11-01 03:31 UTC, gr2m commented on test.js
> +  req.headers['x-hub-signature'] = h.sign(json)
nice 👍

2017-11-01 03:32 UTC, gr2m approved these changes
:shipit:

2017-11-02 15:12 UTC, merged